<a href="https://colab.research.google.com/github/Tsung-Hung/dummy-git/blob/master/%E6%AD%A1%E8%BF%8E%E4%BD%BF%E7%94%A8_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 
import torch.nn as nn

# LayerNorm replace by BatchNorm

In [4]:
batch, sentence_length, embedding_dim = 10, 3, 5
embedding = torch.randn(batch, sentence_length, embedding_dim)
layer_norm = nn.LayerNorm(embedding_dim)
# Activate module
layer_norm(embedding)

tensor([[[ 1.8599, -1.0732, -0.0081, -0.1825, -0.5962],
         [ 0.3421,  0.5905,  1.1613, -0.3421, -1.7518],
         [-0.6546, -0.0478, -1.1937,  0.1276,  1.7686]],

        [[ 0.9122, -0.5494,  0.2260,  1.0550, -1.6437],
         [-1.6339,  1.0804, -0.2343, -0.2377,  1.0255],
         [-0.4407, -0.4257, -1.3807,  1.4345,  0.8126]],

        [[-0.0100, -0.8006,  1.5021, -1.3110,  0.6194],
         [-0.2305,  1.9685, -0.7868, -0.4687, -0.4825],
         [-0.6452, -1.2426,  1.4481,  0.8701, -0.4304]],

        [[-1.2780,  0.6840,  0.3786,  1.2765, -1.0611],
         [ 0.4832, -1.7623,  1.0547, -0.3992,  0.6237],
         [ 1.7316, -0.8269,  0.3565, -0.1862, -1.0751]],

        [[ 0.5504,  1.0564, -1.7367,  0.5925, -0.4626],
         [-1.9730,  0.2944,  0.6897,  0.6613,  0.3277],
         [ 1.6474, -0.0156, -1.0331, -1.0202,  0.4214]],

        [[-1.2974,  0.2724, -0.5536, -0.1299,  1.7085],
         [ 1.2766,  1.0353, -1.0963, -0.1850, -1.0307],
         [ 0.7703, -0.6027,  1.1818, -

In [13]:
def Layer_norm(x):
    batch, sentence_length, embedding_dim = x.shape
    x = x.reshape(1, batch*sentence_length, embedding_dim, 1)
    print(x.shape)
    layer_norm = nn.BatchNorm2d(x.shape[1], track_running_stats=False, affine=True)
    output = layer_norm(x)
    output = output.reshape(output.shape[1], output.shape[2]).reshape(batch, sentence_length, embedding_dim)
    return output

test = Layer_norm(embedding)
test

torch.Size([1, 30, 5, 1])


tensor([[[ 1.8599, -1.0732, -0.0081, -0.1825, -0.5962],
         [ 0.3421,  0.5905,  1.1613, -0.3421, -1.7518],
         [-0.6546, -0.0478, -1.1937,  0.1276,  1.7686]],

        [[ 0.9122, -0.5494,  0.2260,  1.0550, -1.6437],
         [-1.6339,  1.0804, -0.2343, -0.2377,  1.0255],
         [-0.4407, -0.4257, -1.3807,  1.4345,  0.8126]],

        [[-0.0100, -0.8006,  1.5021, -1.3110,  0.6194],
         [-0.2305,  1.9685, -0.7868, -0.4687, -0.4825],
         [-0.6452, -1.2426,  1.4481,  0.8701, -0.4304]],

        [[-1.2780,  0.6840,  0.3786,  1.2765, -1.0611],
         [ 0.4832, -1.7623,  1.0547, -0.3992,  0.6237],
         [ 1.7316, -0.8269,  0.3565, -0.1862, -1.0751]],

        [[ 0.5504,  1.0564, -1.7367,  0.5925, -0.4626],
         [-1.9730,  0.2944,  0.6897,  0.6613,  0.3277],
         [ 1.6474, -0.0156, -1.0331, -1.0202,  0.4214]],

        [[-1.2974,  0.2724, -0.5536, -0.1299,  1.7085],
         [ 1.2766,  1.0353, -1.0963, -0.1850, -1.0307],
         [ 0.7703, -0.6027,  1.1818, -

# matmul 4D tensor

In [2]:
a1 = torch.rand(2,2,4,8)
a2 = torch.rand(2,2,6,8)

result = torch.matmul(a1, a2.transpose(-2,-1))
print('Shape : ', result.shape)
result

Shape :  torch.Size([2, 2, 4, 6])


tensor([[[[3.5439, 2.9560, 2.7772, 3.9363, 3.4186, 2.8114],
          [2.5087, 2.0192, 2.0113, 2.2172, 2.2267, 1.7332],
          [2.9531, 2.4086, 2.1335, 2.9018, 1.9292, 2.6375],
          [2.7683, 2.2980, 2.2833, 3.2471, 2.3955, 2.3795]],

         [[2.0654, 1.5485, 0.7727, 1.3474, 2.1318, 2.7252],
          [1.9204, 2.0794, 0.6779, 1.4825, 1.8152, 2.9874],
          [1.6400, 1.8855, 0.6212, 1.6540, 2.2123, 3.4510],
          [1.6438, 1.2472, 0.6591, 0.9081, 1.6807, 2.1922]]],


        [[[2.2484, 1.9139, 1.1007, 2.1397, 0.4913, 1.5439],
          [2.3228, 2.2215, 2.0116, 2.2048, 0.7323, 1.6595],
          [2.9425, 2.0890, 1.8181, 2.3023, 0.7836, 1.4039],
          [2.0623, 2.3245, 1.7330, 1.9621, 0.7307, 1.2182]],

         [[1.7489, 2.5604, 2.1668, 3.0693, 2.6092, 1.6370],
          [2.2356, 1.7715, 2.4803, 2.8954, 2.5324, 2.0765],
          [2.0889, 2.3783, 2.4830, 2.9700, 2.4808, 2.1869],
          [2.3668, 2.0330, 2.7988, 3.1784, 2.8252, 2.2808]]]])

In [3]:
def new_matmul1(a1,a2):

    k = a1.shape[0]*a1.shape[1]    
    mul_list = []
    for i in range(a1.shape[0]):
        for j in range(a1.shape[1]):
            
            mul = torch.matmul(a1[i,j,:],a2[i,j,:])                
            mul_list.append(mul)

    combine = torch.stack(mul_list)  
    combine = combine.view(a1.shape[0],a1.shape[1],combine.shape[1],combine.shape[2])
    
    return combine

result1 = new_matmul1(a1, a2.transpose(-2,-1))
print('Shape : ', result1.shape)
print(result1)

Shape :  torch.Size([2, 2, 4, 6])
tensor([[[[3.5439, 2.9560, 2.7772, 3.9363, 3.4186, 2.8114],
          [2.5087, 2.0192, 2.0113, 2.2172, 2.2267, 1.7332],
          [2.9531, 2.4086, 2.1335, 2.9018, 1.9292, 2.6375],
          [2.7683, 2.2980, 2.2833, 3.2471, 2.3955, 2.3795]],

         [[2.0654, 1.5485, 0.7727, 1.3474, 2.1318, 2.7252],
          [1.9204, 2.0794, 0.6779, 1.4825, 1.8152, 2.9874],
          [1.6400, 1.8855, 0.6212, 1.6540, 2.2123, 3.4510],
          [1.6438, 1.2472, 0.6591, 0.9081, 1.6807, 2.1922]]],


        [[[2.2484, 1.9139, 1.1007, 2.1397, 0.4913, 1.5439],
          [2.3228, 2.2215, 2.0116, 2.2048, 0.7323, 1.6595],
          [2.9425, 2.0890, 1.8181, 2.3023, 0.7836, 1.4039],
          [2.0623, 2.3245, 1.7330, 1.9621, 0.7307, 1.2182]],

         [[1.7489, 2.5604, 2.1668, 3.0693, 2.6092, 1.6370],
          [2.2356, 1.7715, 2.4803, 2.8954, 2.5324, 2.0765],
          [2.0889, 2.3783, 2.4830, 2.9700, 2.4808, 2.1869],
          [2.3668, 2.0330, 2.7988, 3.1784, 2.8252, 2.2808]

In [4]:
def new_matmul2(a1, a2):

    combine = torch.stack([torch.matmul(a1[i][j], a2[i][j]) for i in range(a1.shape[0]) for j in range(a1.shape[1])], dim=0)        
    return combine.reshape(a1.shape[0], a1.shape[1], a1.shape[2], a2.shape[3])

result2 = new_matmul1(a1, a2.transpose(-2,-1))
print('Shape : ', result2.shape)
print(result2)
print(torch.all(result==result2))

Shape :  torch.Size([2, 2, 4, 6])
tensor([[[[3.5439, 2.9560, 2.7772, 3.9363, 3.4186, 2.8114],
          [2.5087, 2.0192, 2.0113, 2.2172, 2.2267, 1.7332],
          [2.9531, 2.4086, 2.1335, 2.9018, 1.9292, 2.6375],
          [2.7683, 2.2980, 2.2833, 3.2471, 2.3955, 2.3795]],

         [[2.0654, 1.5485, 0.7727, 1.3474, 2.1318, 2.7252],
          [1.9204, 2.0794, 0.6779, 1.4825, 1.8152, 2.9874],
          [1.6400, 1.8855, 0.6212, 1.6540, 2.2123, 3.4510],
          [1.6438, 1.2472, 0.6591, 0.9081, 1.6807, 2.1922]]],


        [[[2.2484, 1.9139, 1.1007, 2.1397, 0.4913, 1.5439],
          [2.3228, 2.2215, 2.0116, 2.2048, 0.7323, 1.6595],
          [2.9425, 2.0890, 1.8181, 2.3023, 0.7836, 1.4039],
          [2.0623, 2.3245, 1.7330, 1.9621, 0.7307, 1.2182]],

         [[1.7489, 2.5604, 2.1668, 3.0693, 2.6092, 1.6370],
          [2.2356, 1.7715, 2.4803, 2.8954, 2.5324, 2.0765],
          [2.0889, 2.3783, 2.4830, 2.9700, 2.4808, 2.1869],
          [2.3668, 2.0330, 2.7988, 3.1784, 2.8252, 2.2808]

In [9]:
def new_matmul3(a1, a2):
  '''  
  a1 = (2,2,4,8)  
  a2 = (2,2,6,8) 
  torch(a2, a1.T)
  '''
  B1, N1, H1, T1 = a1.shape 
  B2, N2, H2, T2 = a2.shape 
  a1 = a1.reshape(B1 * N1 * H1, T1)
  #print('a1 : ', a1.shape)
  #a2 = a2.transpose(-2,-1)
  a2 = a2.permute(2,0,1,3)
  a2 = a2.reshape(T2, B2 * N2 * H2)
  #print('a2 : ', a2.shape)
  result = torch.matmul(a1, a2) 
  result = torch.stack([result[i*H1:(i+1)*H1 ,i*H2:(i+1)*H2] for i in range(B1*N1)])
  result = result.reshape(B1,N1,H1,H2)
  return result

result3 = new_matmul3(a1, a2)
print('Shape : ', result3.shape)
print(result3)

Shape :  torch.Size([1, 4, 15000, 100])
tensor([[[[4.1306, 4.1551, 2.8209,  ..., 2.6060, 3.3173, 3.6580],
          [6.1360, 6.2356, 3.8443,  ..., 4.3643, 5.3529, 6.4149],
          [5.7874, 4.8149, 3.3059,  ..., 3.8239, 4.6116, 5.6743],
          ...,
          [4.2056, 4.1895, 3.1463,  ..., 3.3322, 3.7732, 3.9175],
          [3.9175, 4.0749, 3.3967,  ..., 3.0140, 3.3787, 4.5128],
          [4.8084, 3.9714, 2.4514,  ..., 3.3708, 4.1949, 4.6743]],

         [[3.3599, 3.2117, 3.7189,  ..., 4.0706, 4.4173, 4.6591],
          [3.7905, 3.2209, 4.2085,  ..., 4.3113, 5.3437, 4.5953],
          [2.5402, 2.6899, 2.5743,  ..., 3.1548, 3.6519, 3.4797],
          ...,
          [3.3800, 3.5784, 4.9551,  ..., 4.0804, 5.1566, 4.5895],
          [3.6987, 3.1677, 3.1631,  ..., 4.3601, 4.8928, 4.5060],
          [4.1681, 4.5183, 5.3103,  ..., 4.6569, 6.5011, 5.2103]],

         [[5.1613, 5.0629, 4.3831,  ..., 3.2147, 5.3007, 4.8530],
          [5.0414, 4.9240, 4.2724,  ..., 3.6605, 5.5004, 4.0971],
  

In [37]:
def new_matmul4(a1, a2):
  '''
  a1 = (2,2,4,8)  
  a2 = (2,2,6,8)
  a1_matrix = (16,32)
  a2_matrix = (32,24)
  '''
  a1_matrix = torch.block_diag(*[a1[i][j] for i in range(a1.shape[0]) for j in range(a1.shape[1])])
  a2_matrix = torch.block_diag(*[a2[i][j] for i in range(a2.shape[0]) for j in range(a2.shape[1])])
  #identity = torch.cat([torch.eye(a2.shape[3]) for _ in range(a2.shape[0]*a2.shape[1])]).cuda()
  result = torch.matmul(a1_matrix, a2_matrix)
  #result = torch.matmul(result, identity)
  return result

result4 = new_matmul4(a1,a2.transpose(-2,-1))
print('Shape : ', result4.shape)
print(result4)

Shape :  torch.Size([60000, 4000])
tensor([[3.5483, 4.6493, 4.3385,  ..., 0.0000, 0.0000, 0.0000],
        [3.5493, 5.0386, 3.7879,  ..., 0.0000, 0.0000, 0.0000],
        [4.0197, 4.8545, 3.7965,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 4.8666, 3.8366, 4.2866],
        [0.0000, 0.0000, 0.0000,  ..., 3.7308, 3.0926, 3.4936],
        [0.0000, 0.0000, 0.0000,  ..., 2.6934, 2.1872, 1.7510]],
       device='cuda:0')


In [32]:
a1 = torch.rand(1,4,15000,16).cuda()
a2 = torch.rand(1,4,1000,16).cuda()

%timeit -n 100 -r 7 torch.matmul(a1, a2.transpose(-2,-1))

22.5 µs ± 2.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
%timeit -n 100 -r 7 new_matmul1(a1, a2.transpose(-2,-1))

The slowest run took 20.44 times longer than the fastest. This could mean that an intermediate result is being cached.
3.11 ms ± 1.2 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
%timeit -n 100 -r 7 new_matmul2(a1, a2.transpose(-2,-1))

3.55 ms ± 68.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [35]:
%timeit -n 200 -r 7 new_matmul3(a1, a2)

5.83 ms ± 1.94 ms per loop (mean ± std. dev. of 7 runs, 200 loops each)


In [39]:
%timeit -n 100 -r 7 new_matmul4(a1, a2.transpose(-2,-1))

The slowest run took 8.23 times longer than the fastest. This could mean that an intermediate result is being cached.
6.62 ms ± 2.32 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
